#!/bin/bash

echo "🚀 COMPLETE PRODUCTION DEPLOYMENT GUIDE"
echo "======================================="
echo ""
echo "🎯 Issue: Production server has old authentication middleware"
echo "✅ Solution: Upload 2 fixed files to cPanel"
echo ""

echo "📋 FILES TO UPLOAD:"
echo ""
echo "1️⃣  src/middleware/adminAuth.js"
echo "   ↳ Location: /public_html/backend.shilpgroup.com/src/middleware/"
echo "   ↳ Purpose: Fixed authentication that works with JWT tokens"
echo ""
echo "2️⃣  src/services/adminService.js"  
echo "   ↳ Location: /public_html/backend.shilpgroup.com/src/services/"
echo "   ↳ Purpose: Generates proper JWT tokens"
echo ""

echo "🔑 NEW ADMIN CREDENTIALS (Already Created in Database):"
echo "   📧 Email: shilpgroup47@gmail.com"
echo "   🔑 Password: ShilpGroup@RealState11290"
echo "   👤 Role: super_admin"
echo ""

echo "🚀 DEPLOYMENT STEPS:"
echo ""
echo "Step 1: Upload Files via cPanel File Manager"
echo "   • Go to cPanel → File Manager"
echo "   • Navigate to /public_html/backend.shilpgroup.com/"
echo "   • Upload src/middleware/adminAuth.js (overwrite existing)"
echo "   • Upload src/services/adminService.js (overwrite existing)"
echo ""
echo "Step 2: Restart Node.js Application"
echo "   • Go to cPanel → Setup Node.js App"
echo "   • Find backend.shilpgroup.com app"
echo "   • Click 'Restart' button"
echo ""
echo "Step 3: Test APIs (Should all work after restart)"
echo "   ✅ Login: POST /api/admin/login"
echo "   ✅ Profile: GET /api/admin/profile"
echo "   ✅ Projects: GET/POST/PUT/DELETE /api/projects/*"
echo "   ✅ Banners: GET/POST/PUT/DELETE /api/banners/*"
echo "   ✅ Blogs: GET/POST/PUT/DELETE /api/blogs/*"
echo "   ✅ File Upload: POST /api/banners/*/upload"
echo ""

echo "🧪 TEST COMMANDS (Run after deployment):"
echo ""
echo "# Test Login"
echo 'curl -X POST "https://backend.shilpgroup.com/api/admin/login" \'
echo '  -H "Content-Type: application/json" \'
echo '  -d '"'"'{"email":"shilpgroup47@gmail.com","password":"ShilpGroup@RealState11290"}'"'"
echo ""
echo "# Test Profile (use token from login response)"
echo 'curl -X GET "https://backend.shilpgroup.com/api/admin/profile" \'
echo '  -H "Authorization: Bearer YOUR_JWT_TOKEN"'
echo ""
echo "# Test Projects"
echo 'curl -X GET "https://backend.shilpgroup.com/api/projects" \'
echo '  -H "Authorization: Bearer YOUR_JWT_TOKEN"'
echo ""

echo "⚠️  IMPORTANT NOTES:"
echo "• The files must be uploaded to the exact paths shown above"
echo "• Node.js app MUST be restarted after uploading files"
echo "• Test login first, then test other APIs with the JWT token"
echo "• All admin functions will work after successful deployment"
echo ""
echo "🎯 Expected Result: All CRUD operations for projects, banners, blogs will work!"